# Generated by Django 3.1.6 on 2021-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employeeId',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
