# Generated by Django 3.1.6 on 2021-02-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_employees_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to='Employee.employees'),
        ),
    ]
