# Generated by Django 3.1.6 on 2021-02-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20210211_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_attendance', to='Employee.attendance'),
        ),
    ]
