# Generated by Django 3.1.6 on 2021-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20210211_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanagement',
            name='income',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmanagement',
            name='outcome',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
