# Generated by Django 3.1.6 on 2021-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingBy', models.CharField(choices=[('SM', 'Shamim Osman'), ('SF', 'Shariful Islam'), ('MN', 'Mamunur Rashid'), ('TN', 'Tuhin Hossain'), ('JD', 'Jabed'), ('AL', 'Amirul Sohan'), ('MI', 'Mehedi Hasan Moni'), ('RY', 'Rony Hossen')], default='', max_length=2)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date_published')),
            ],
        ),
    ]
