# Generated by Django 3.1.6 on 2021-02-07 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_recieve_person', models.CharField(choices=[('SM', 'Shamim Osman'), ('SF', 'Shariful Islam'), ('MN', 'Mamunur Rashid'), ('TN', 'Tuhin Hossain'), ('JD', 'Jabed'), ('AL', 'Amirul Sohan'), ('MI', 'Mehedi Hasan Moni'), ('RY', 'Rony Hossen')], default='', max_length=2)),
                ('order_recieve_date', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('order_recieve_fiverr_account', models.CharField(max_length=20)),
                ('order_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_amount_minus_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_charges_for_fiverr', models.FloatField(blank=True, default=0.0, null=True)),
                ('client_fiverr_id', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=20)),
                ('client_email_address', models.EmailField(max_length=254)),
                ('order_page_url', models.URLField()),
                ('order_spreadsheet_url', models.URLField()),
                ('order_remarks', models.CharField(blank=True, max_length=50)),
                ('order_working_team_or_person_name', models.CharField(blank=True, max_length=50)),
                ('order_status', models.CharField(choices=[('NRA', 'NRA'), ('WIP', 'WIP'), ('NE', 'NE'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Revision', 'Revision'), ('Issues', 'Issues'), ('Cancelled', 'Cancelled')], default='', max_length=15)),
                ('order_delivery_person', models.CharField(choices=[('SM', 'Shamim Osman'), ('SF', 'Shariful Islam'), ('MN', 'Mamunur Rashid'), ('TN', 'Tuhin Hossain'), ('JD', 'Jabed'), ('AL', 'Amirul Sohan'), ('MI', 'Mehedi Hasan Moni'), ('RY', 'Rony Hossen')], default='', max_length=2)),
                ('order_delivery_date', models.DateField(blank=True, default=datetime.date.today)),
                ('order_delivery_amount', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
