# Generated by Django 3.1.6 on 2021-02-04 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='accountFiverr',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
