# Generated by Django 3.1.6 on 2021-02-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0002_auto_20210204_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='actualAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
