# Generated by Django 3.1.6 on 2021-02-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0003_auto_20210204_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='chargesFiverr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='clientName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='emailAddress',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='fiverrId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='orderPageURL',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='spreadsheetLink',
            field=models.URLField(default=''),
        ),
    ]
