# Generated by Django 3.1.6 on 2021-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0003_incdelivery_marketplacename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incdelivery',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='order_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='order_spreadsheet_url',
            field=models.URLField(blank=True),
        ),
    ]
