# Generated by Django 3.1.6 on 2021-02-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0004_auto_20210205_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incdelivery',
            name='clientName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='orderPageURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='spreadsheetLink',
            field=models.URLField(),
        ),
    ]
