# Generated by Django 3.1.6 on 2021-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0004_auto_20210207_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incdelivery',
            name='marketplacename',
            field=models.CharField(choices=[('Fiverr', 'Fiverr'), ('Upwork', 'Upwork'), ('PeoplePerHour', 'PeoplePerHour'), ('Others', 'Others')], default='', max_length=100),
        ),
    ]
