# Generated by Django 3.1.6 on 2021-02-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20210211_1208'),
        ('income_deliveris', '0005_auto_20210208_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Employee.employees'),
            preserve_default=False,
        ),
    ]
