# Generated by Django 3.1.6 on 2021-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0005_auto_20210205_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incdelivery',
            old_name='actualAmount',
            new_name='deliveredAmount',
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='clientName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
