# Generated by Django 3.1.6 on 2021-02-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20210211_1208'),
        ('income_deliveris', '0006_incdelivery_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incdelivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Employee.employees'),
        ),
    ]
