# Generated by Django 3.1.6 on 2021-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0006_auto_20210206_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='allocationTeamName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incdelivery',
            name='orderStatus',
            field=models.CharField(choices=[('NRA', 'NRA'), ('WIP', 'WIP'), ('NE', 'NE'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Revision', 'Revision'), ('Issues', 'Issues'), ('Cancelled', 'Cancelled')], default='', max_length=15),
        ),
    ]
