# Generated by Django 3.1.6 on 2021-02-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0007_auto_20210206_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='deliveredBy',
            field=models.CharField(choices=[('SM', 'Shamim Osman'), ('SF', 'Shariful Islam'), ('MN', 'Mamunur Rashid'), ('TN', 'Tuhin Hossain'), ('JD', 'Jabed'), ('AL', 'Amirul Sohan'), ('MI', 'Mehedi Hasan Moni'), ('RY', 'Rony Hossen')], default='', max_length=2),
        ),
    ]
