# Generated by Django 3.1.6 on 2021-02-06 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0008_incdelivery_deliveredby'),
    ]

    operations = [
        migrations.AddField(
            model_name='incdelivery',
            name='deliveredDate',
            field=models.DateField(default=datetime.datetime(2021, 2, 6, 4, 49, 8, 612995, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incdelivery',
            name='deliveredAmount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
