# Generated by Django 3.1.6 on 2021-02-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_deliveris', '0009_auto_20210206_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incdelivery',
            name='deliveredDate',
            field=models.DateField(null=True),
        ),
    ]
