# Generated by Django 3.1.6 on 2021-02-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0012_auto_20210211_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplaces', models.CharField(choices=[('Fiverr', 'Fiverr'), ('Upwork', 'Upwork'), ('PeoplePerHour', 'PeoplePerHour'), ('Others', 'Others')], default='', max_length=100)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_receive', to='Employee.clientmanagement')),
            ],
        ),
    ]
