# Generated by Django 3.1.6 on 2021-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='marketplaces',
        ),
        migrations.AddField(
            model_name='order',
            name='SpreadSheet',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='market_place_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_page_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='percentage',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_account',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
